baseurl = "http://localhost/"
languageCode = "en-us"
title = "Encounters with the World Wild Web"
theme = "hugo_theme_robust"

[Params]
  Author = "David Lauzon"
  GitHubUser = "davidonlaptop"
  disqusShortname = "davidlauzon"
